jsuto/piler

docker/docker-compose.yaml
util/automated-search.php
util/daily-report.php
util/generate_stats.php
webui/model/saas/customer.php
webui/model/search/message.php

Memcached fix

---

config.php.in
webui/view/theme/default/templates/common/layout-audit-removal.tpl
webui/view/theme/default/templates/common/layout-audit.tpl
webui/view/theme/default/templates/common/layout-email.tpl
webui/view/theme/default/templates/common/layout-search-mobile.tpl
webui/view/theme/default/templates/common/layout-search.tpl
webui/view/theme/default/templates/common/layout.tpl

jquery-3.7.1 and jquery-ui-1.13.3

Updated jquery and jquery-ui

---

docker/Dockerfile

Updated Dockerfile with sudoers fix

---

.github/actions/build/package/action.yaml
.github/workflows/test.yaml
build/Dockerfile
build/README.md
config.php.in
contrib/webserver/piler-nginx.conf
docker/Dockerfile
docker/start.sh
etc/manticore.conf.in
unit_tests/run.sh
webui/controller/audit/helper.php
webui/controller/login/logout.php
webui/controller/search/helper.php
webui/model/audit/audit.php
webui/system/database/sphinx.php
webui/system/misc.php
webui/templates/audit/helper.tpl

Write audit records to manticore real time index

---

src/mysql.c
src/piler.c
util/config-site.php.in
util/postinstall.sh.in

Fixed postinstall utility

---

webui/model/user/prefs.php

Removed unused DIR_THEME constant

---

etc/manticore.conf.in

Added buddy_path variable

---

webui/controller/message/view.php
webui/model/message/attachment.php

Display svg images in preview pane

---

util/imapfetch.py
webui/controller/import/test.php
webui/templates/import/list.tpl

first try. works but might be messy yet

Add TLS support to Imap Import

---

config.php.in

Fixed memcached server settings

---

webui/controller/import/remove.php
webui/model/user/user.php
webui/templates/common/menu.tpl
webui/templates/user/list.tpl

Minor gui fixes

---

docker/docker-compose.yaml
docker/piler.cnf

[FEATURE] Docker: add custom mariadb cnf

---

webui/language/cn/messages.php
webui/language/cz/messages.php
webui/language/de/messages.php
webui/language/en/messages.php
webui/language/es/messages.php
webui/language/fr/messages.php
webui/language/hu/messages.php
webui/language/it/messages.php
webui/language/pl/messages.php
webui/language/pt/messages.php
webui/language/ru/messages.php
webui/language/tr/messages.php
webui/language/tw/messages.php
webui/templates/policy/archiving.tpl
webui/templates/policy/folder.tpl
webui/templates/policy/retention.tpl

Added "Cc" to "To" in policy templates

---

webui/controller/policy/archiving.php
webui/model/policy/archiving.php
webui/templates/policy/archiving.tpl

Added sorting to archiving policy

---

webui/controller/group/add.php
webui/controller/group/edit.php
webui/controller/group/remove.php
webui/controller/login/ga.php
webui/controller/message/pdf.php
webui/templates/message/auto.tpl

Fixed SITE_URL related URIs

---

config.php.in

Reorganized PATH_PREFIX settings

---

webui/model/health/health.php
webui/templates/health/worker.tpl

Health page displayes memcached status

---

docker/docker-compose.yaml
docker/start.sh

Change "manticore" to "${MANTICORE_HOSTNAME}"
Fixed #160

introduce MANTICORE_HOSTNAME

---

webui/controller/message/pdf.php

pdf export shall contain the header information

---

webui/templates/message/view.tpl
webui/templates/search/helper.tpl

Restored the restore message feature for mobile view

---

config.php.in
webui/controller/message/view.php
webui/templates/message/view.tpl

There's a new DATE_PREVIEW_TEMPLATE variable to allow you to define the date format.

Preview pane date header is the fixed value to your local timezone

---

webui/controller/search/helper.php

Use the 'from: email@address' for to search only the From/Sender fields.

By default search email address in the whole email

---

configure
configure.in
etc/example.conf
src/cfg.c
src/cfg.h
src/decoder.c
src/decoder.h
src/defs.h
src/import_imap.c
src/pilerimport.c
tests/setup.sh

The imap server should be specified as **imap://hostname:143** or **imaps://hostname:993** formats.
Also you need libcurl development package to build piler.

pilerimport uses libcurl to download emails from imap server

---

src/import_imap.c

Reimplemented -f for pilerimport

---

src/parser.c

Prefer the date from the 1st Received: header line

---

util/imapfetch.py

Open the imap connection as read-only by default

---

src/import_imap.c

Use relative uids for imap download

---

config.php.in
webui/model/search/message.php
webui/model/search/search.php

Introduced DATE_TEMPLATE_SEARCH_HITS for search results date formatting

---

config.php.in
webui/controller/message/view.php
webui/templates/message/view.tpl

Allow auditors to print the complete header when viewing the message
